/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestióndepersonal;

import java.sql.SQLException;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author CFL 401
 */
public class testVentana extends javax.swing.JFrame {

    
    /**
     * Creates new form testVentana
     */
    public testVentana() {
        initComponents();
     
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldCrearTablaC = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fieldID = new javax.swing.JTextField();
        fieldApellido = new javax.swing.JTextField();
        fieldNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fieldCrearTabla = new javax.swing.JTextField();
        fieldCrearColumnas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        fieldIngresar = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JToggleButton();
        btnActualizar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnExiste = new javax.swing.JButton();
        btnConectar = new javax.swing.JButton();
        textoEstado = new javax.swing.JLabel();
        fieldActualizar = new javax.swing.JTextField();
        fieldExiste = new javax.swing.JTextField();
        fieldBorrar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellido");

        fieldID.setEnabled(false);
        fieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldIDActionPerformed(evt);
            }
        });

        fieldApellido.setEnabled(false);
        fieldApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldApellidoActionPerformed(evt);
            }
        });

        fieldNombre.setEnabled(false);
        fieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNombreActionPerformed(evt);
            }
        });

        jLabel4.setText("Texto de informe.");

        fieldCrearTabla.setEditable(false);
        fieldCrearTabla.setText("nomTabla");
        fieldCrearTabla.setToolTipText("iygjyguyguyj");

        fieldCrearColumnas.setEditable(false);
        fieldCrearColumnas.setText("columnas");

        jLabel6.setText("Tabla");

        btnCrear.setText("Crear");
        btnCrear.setEnabled(false);
        btnCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearMouseClicked(evt);
            }
        });

        fieldIngresar.setEditable(false);

        btnIngresar.setText("Ingresar");
        btnIngresar.setEnabled(false);

        btnActualizar.setText("Actualizar");
        btnActualizar.setEnabled(false);

        btnBorrar.setText("Borrar");
        btnBorrar.setEnabled(false);

        btnExiste.setText("Existe");
        btnExiste.setEnabled(false);

        btnConectar.setText("Conectar");
        btnConectar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConectarMouseClicked(evt);
            }
        });
        btnConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarActionPerformed(evt);
            }
        });

        textoEstado.setText("Desconectado");

        fieldActualizar.setEditable(false);

        fieldExiste.setEditable(false);

        fieldBorrar.setEditable(false);

        jLabel8.setText("Tabla");

        jLabel9.setText("Tabla");

        jLabel10.setText("Tabla");

        jLabel11.setText("Tabla");

        jLabel12.setText("Tabla");

        javax.swing.GroupLayout fieldCrearTablaCLayout = new javax.swing.GroupLayout(fieldCrearTablaC);
        fieldCrearTablaC.setLayout(fieldCrearTablaCLayout);
        fieldCrearTablaCLayout.setHorizontalGroup(
            fieldCrearTablaCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fieldCrearTablaCLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(fieldCrearTablaCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fieldCrearTablaCLayout.createSequentialGroup()
                        .addGroup(fieldCrearTablaCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(113, 113, 113)
                        .addGroup(fieldCrearTablaCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(51, 51, 51))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fieldCrearTablaCLayout.createSequentialGroup()
                .addGroup(fieldCrearTablaCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(fieldCrearTablaCLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, fieldCrearTablaCLayout.createSequentialGroup()
                        .addGroup(fieldCrearTablaCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, fieldCrearTablaCLayout.createSequentialGroup()
                                .addGroup(fieldCrearTablaCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(fieldCrearTablaCLayout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(jLabel5)
                                        .addGap(48, 48, 48))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fieldCrearTablaCLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(fieldCrearTablaCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel11))
                                        .addGap(29, 29, 29)))
                                .addGroup(fieldCrearTablaCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fieldActualizar)
                                    .addComponent(fieldIngresar)
                                    .addComponent(fieldCrearTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                    .addComponent(fieldExiste, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                    .addComponent(fieldBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(fieldCrearColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, fieldCrearTablaCLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(textoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(fieldCrearTablaCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fieldCrearTablaCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnExiste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                        .addComponent(btnIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnConectar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
        fieldCrearTablaCLayout.setVerticalGroup(
            fieldCrearTablaCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fieldCrearTablaCLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(fieldCrearTablaCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(fieldCrearTablaCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fieldCrearTablaCLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fieldCrearTablaCLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addGroup(fieldCrearTablaCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(fieldCrearTablaCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fieldCrearTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldCrearColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(btnCrear)
                    .addComponent(jLabel12))
                .addGap(35, 35, 35)
                .addGroup(fieldCrearTablaCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIngresar)
                    .addComponent(jLabel8))
                .addGap(30, 30, 30)
                .addGroup(fieldCrearTablaCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(fieldActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(34, 34, 34)
                .addGroup(fieldCrearTablaCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrar)
                    .addComponent(fieldBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(31, 31, 31)
                .addGroup(fieldCrearTablaCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExiste)
                    .addComponent(fieldExiste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(111, 111, 111)
                .addGroup(fieldCrearTablaCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConectar)
                    .addComponent(textoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fieldCrearTablaC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fieldCrearTablaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNombreActionPerformed

    private void fieldApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldApellidoActionPerformed

    private void fieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldIDActionPerformed

    private void btnConectarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConectarMouseClicked

        if (btnConectar.getText().equals("Conectar") && GestionDePersonal.getConexionDB() == null) {

            DatosDeConexion datosDeConexion = new DatosDeConexion();
            setVisible(false);
            datosDeConexion.setVisible(true);

        } else if (btnConectar.getText().equals("Conectar") && GestionDePersonal.getConexionDB() != null) {
            System.out.println(GestionDePersonal.getConexionDB().conectarADB());
            Activar();
            btnConectar.setText("Desconectar");
            textoEstado.setText("Conectado");
        }

        else  if (btnConectar.getText().equals("Desconectar")) {

            try {

                GestionDePersonal.getConexionDB().cerrarConex();
                Desactivar();
                btnConectar.setText("Conectar");
                textoEstado.setText("Desconectado");
            } catch (SQLException ex) {
                Logger.getLogger(testVentana.class.getName()).log(Level.SEVERE, null, ex);
            }

        }


    }//GEN-LAST:event_btnConectarMouseClicked

    private void btnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarActionPerformed


    }//GEN-LAST:event_btnConectarActionPerformed

    private void btnCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseClicked

       String nombreTabla= fieldCrearTabla.getText();
       String columnas= fieldCrearColumnas.getText();
        
        try {
            GestionDePersonal.getConexionDB().crearTabla(nombreTabla, columnas);
        } catch (SQLException ex) {
            System.out.println("No se creó la tabla");
        }
            
        
        
        
        
        
        
    }//GEN-LAST:event_btnCrearMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(testVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(testVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(testVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new testVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnConectar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnExiste;
    private javax.swing.JToggleButton btnIngresar;
    private javax.swing.JTextField fieldActualizar;
    private javax.swing.JTextField fieldApellido;
    private javax.swing.JTextField fieldBorrar;
    private javax.swing.JTextField fieldCrearColumnas;
    private javax.swing.JTextField fieldCrearTabla;
    private javax.swing.JPanel fieldCrearTablaC;
    private javax.swing.JTextField fieldExiste;
    private javax.swing.JTextField fieldID;
    private javax.swing.JTextField fieldIngresar;
    private javax.swing.JTextField fieldNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel textoEstado;
    // End of variables declaration//GEN-END:variables

    public void Activar() {

        btnCrear.setEnabled(true);
        btnIngresar.setEnabled(true);
        btnExiste.setEnabled(true);
        btnBorrar.setEnabled(true);
        btnActualizar.setEnabled(true);
        fieldIngresar.setEditable(true);
        fieldExiste.setEditable(true);
        fieldBorrar.setEditable(true);
        fieldActualizar.setEditable(true);
        fieldCrearTabla.setEditable(true);
        fieldCrearColumnas.setEditable(true);
        fieldNombre.setEditable(true);
        fieldApellido.setEditable(true);
        fieldID.setEditable(true);
        fieldNombre.setEnabled(true);
        fieldApellido.setEnabled(true);
        fieldID.setEnabled(true);
        btnConectar.setText("Desconectar");
        textoEstado.setText("Conectado");
        
        

    }

    public void Desactivar() {

        btnCrear.setEnabled(false);
        btnIngresar.setEnabled(false);
        btnExiste.setEnabled(false);
        btnBorrar.setEnabled(false);
        btnActualizar.setEnabled(false);
        fieldIngresar.setEditable(false);
        fieldExiste.setEditable(false);
        fieldBorrar.setEditable(false);
        fieldActualizar.setEditable(false);
        fieldCrearTabla.setEditable(false);
        fieldCrearColumnas.setEditable(false);
        fieldNombre.setEditable(false);
        fieldApellido.setEditable(false);
        fieldID.setEditable(false);
    }
}
